Login/Models/ErrorViewModel.cs
using System;

namespace Login.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Login/Models/UserModel.cs
using System;

namespace Login.Models
{
    public class UserModel
    {
        public string email { get; set;}
        public string name {get; set;}
        public string id {get; set;}
    }
}

Login/Controllers/EmployeeFormController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Login.Models;

namespace Login.Controllers
{
    public class EmployeeFormController : Controller
    {
        public IActionResult EmployeeForm()
        {
            return View();
        }
    }
}

Login/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Login.Models;

namespace Login.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Login/Controllers/LoginFormController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Login.Models;

namespace Login.Controllers
{
    public class LoginFormController : Controller
    {
        public IActionResult LoginForm()
        {
            return View();
        }
    }
}

Login/Controllers/RegisterFormController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Login.Models;

namespace Login.Controllers
{
    public class RegisterFormController : Controller
    {
        public IActionResult RegisterForm()
        {
            return View();
        }
    }
}

Login/Controllers/ShowEmployeeController.cs
using System;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Login.Models;
using Newtonsoft.Json;

namespace Login.Controllers
{
    public class ShowEmployeeController : Controller
    {
        static HttpClient client = new HttpClient();

        public IActionResult ShowEmployee()
        {
            
            return View();
        }

        public string getTest(){
            return "test";
        }
       
       public static async Task RunAsync()
        {
            client.BaseAddress = new Uri("http://localhost:5001/");
            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(
                new MediaTypeWithQualityHeaderValue("application/json"));

        }

        public static async Task<UserModel> GetUserAsync()
        {
            UserModel user = null;
            HttpResponseMessage response = await client.GetAsync("api/generateuser");
            if (response.IsSuccessStatusCode)
            {
                user = await response.Content.ReadAsAsync<UserModel>();
                
            }
            return user;
        }
    }
}

Login/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Login.Models;

namespace Login.Controllers
{
    public class TestFormController : Controller
    {
        public IActionResult TestForm()
        {
            return View();
        }
    }
}

Login/Controllers/TestGenerateUserController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Login.Models;

namespace Login.Controllers
{
    public class TestGenerateUserController : Controller
    {
        public IActionResult TestGenerateUser()
        {
            return View();
        }
    }
}

Login/Views/EmployeeForm/employeeForm.cshtml
<div ng-controller="EmployeeFormController">
    <div class="container">
        <h3>รายละเอียดเพิ่มเติม</h3>
    <div class="form-group">
        <label >Location</label>
       <select class="form-control" ng-model="employeeform.location" id="">
            <option ></option>
       </select>
    </div>
    <div class="form-group">
        <label for="">Salary</label>
        <input type="text" class="form-control" ng-model="employeeform.salary" placeholder="Salary">
    </div>  
    <div class="form-group">
        <label for="">Position</label>
        <select class="form-control" ng-model="employeeform.position" id="">
            <option ></option>
       </select>
    </div>  
    <button  class="btn btn-default" ng-click="submit(employeeform)">ส่งข้อมูล</button>
    </div>
</div>

@section Scripts {
    <script src="~/js/employeeFormController.js"></script>
}

Login/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Login/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Login/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

Login/Views/LoginForm/loginForm.cshtml
<div ng-controller="LoginFormController">
    <div class="container">
        <h3>Login</h3>
    <div class="form-group">
        <label >Username</label>
        <input type="text" class="form-control" ng-model="loginForm.username" id="" placeholder="username">
    </div>
    <div class="form-group">
        <label for="">Password</label>
        <input type="password" class="form-control" ng-model="loginForm.password" placeholder="password">
    </div>
    
    <button  class="btn btn-default" ng-click="login(loginForm)">Login</button>
    </div>
</div>

@section Scripts {
   <script src="~/js/loginFormController.js"></script>
}

Login/Views/RegisterForm/registerForm.cshtml
<div ng-controller="RegisterFormController">
    <div class="container">
        <h3>ข้อมูล outsource</h3>
    <div class="form-group">
        <label >Email address</label>
        <input type="text" class="form-control" ng-model="registerForm.email" id="" placeholder="Email">
    </div>
    <div class="form-group">
        <label for="">Fullname</label>
        <input type="text" class="form-control" ng-model="registerForm.fullname" placeholder="Fullname">
    </div>
    <div class="form-group">
        <label for="">Experience</label>
        <input type="text" class="form-control" ng-model="registerForm.experience" placeholder="Experience">
    </div>   
    <div class="form-group">
        <label for="">Age</label>
        <input type="text" class="form-control" ng-model="registerForm.age" placeholder="Age">
    </div>
    <div class="form-group">
        <label >Skill</label>
       <select class="form-control" ng-model="employeeform.skill" id="">
            <option></option>
       </select>
    </div>  
    <button  class="btn btn-default" ng-click="sendData(registerForm)">ส่งข้อมูล</button>
    </div>
</div>

@section Scripts {
    <script src="~/js/registerFormController.js"></script>
}

Login/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html ng-app="myapp">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Login</title>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.7.2/angular.min.js"></script>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Login</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-area="" asp-controller="RegisterForm" asp-action="RegisterForm">Register</a></li>
                    <li><a asp-area="" asp-controller="LoginForm" asp-action="LoginForm">Login</a></li>
                    <li><a asp-area="" asp-controller="EmployeeForm" asp-action="EmployeeForm">EmployeeForm</a></li>
                    <li><a asp-area="" asp-controller="ShowEmployee" asp-action="ShowEmployee">ShowEmployee</a></li>
                    <li><a asp-area="" asp-controller="TestGenerateUser" asp-action="TestGenerateUser">ทดสอบสร้าง user</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Login</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
         <script src="~/js/angular.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Login/Views/ShowEmployee/showEmployee.cshtml
<div ng-controller="ShowEmployeeController">
    <div class="container">
        <h3>ข้อมูล outsource</h3>
   <div ng-init="init()">
       <table>
         <tr>
            <th>Email</th>
            <th>name</th> 
            <th>Status</th>
        </tr>
        <tr ng-repeat="em in employees">
            <td>{{em.email}}</td>
            <td>{{em.name}}</td>
            <td>{{em.typeAccount}}</td>
        </tr>
       </table>
       
   </div>
    </div>
</div>

@section Scripts {
    <script src="~/js/showEmployeeController.js"></script>
}

Login/Views/TestForm/testForm.cshtml
<div ng-Controller = "TestController">
    <div class="container">
        <h3>ทดสอบ</h3>
        <div class="form-group">
        <label >กรอกชื่อ-สกุล</label>
        <input type="text" class="form-control" ng-model="testForm.email" id="" placeholder="ชื่อ-สกุล">
        <button  class="btn btn-primary btn-blockt" ng-click="sendData(testForm)">ส่งข้อมูล</button>
    </div>
    </div>
</div>

Login/Views/TestGenerateUser/TestGenerateUser.cshtml
<div ng-controller="TestGenerateUserController">
    <div class="container">
        <h3>ทดสอบ Generate Email</h3>
    <div class="form-group">
        <label >Email address</label>
        <input type="text" class="form-control" ng-model="testEmailGen.email" id="" placeholder="Email">
    </div>
  
    <button  class="btn btn-default" ng-click="sendData(testEmailGen)">ทดสอบ</button>
    </div>
</div>

@section Scripts {
    <script src="~/js/TestGenerateUserController.js"></script>
}